spring.application.name=vault-key
# Remover para baixo, deixar de cima
# Configuração do banco H2 em memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# Dialeto do Hibernate para o H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Mostrar o SQL no console (opcional)
spring.jpa.show-sql=true
# Criar/atualizar automaticamente o schema do banco (opcional)
spring.jpa.hibernate.ddl-auto=update
# Habilitar o console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
